# Generated by Django 5.2.3 on 2025-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='نوع المنتج'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الوزن (كجم)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (ريال)'),
        ),
    ]
