# Generated by Django 5.2.3 on 2025-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
            },
        ),
    ]
