# Generated by Django 5.2.3 on 2025-06-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ad_alter_location_options_location_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'إعلان', 'verbose_name_plural': 'الإعلانات'},
        ),
    ]
