# Generated by Django 5.2.3 on 2025-06-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_remove_listing_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('category', models.CharField(choices=[('electronics', 'إلكترونيات'), ('furniture', 'أثاث'), ('metal', 'معادن'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='الفئة')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], default='used', max_length=20, verbose_name='الحالة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للبيع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='صورة المنتج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
