# Generated by Django 5.2.3 on 2025-06-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_product_delete_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='الرياض', max_length=255, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to=settings.AUTH_USER_MODEL,
                verbose_name='صاحب المنتج',
                null=True,     # ← يسمح بأن يكون فارغًا مؤقتًا
                blank=True     # ← يُسمح بتركه فارغًا في النماذج
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
    ]
